name: linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Installing Packages
        run: yarn install

      - name: Test Linting
        run: yarn lint
